### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Berthold38** [THDMoritzEnderle/BVB-ticket-bot#2]
Hi Moritz

How do you handle the login in the script?
The URL https://www.ticket-onlineshop.com/ols/bvb/de/bundesliga/channel/shop/index is expecting a login.
Thy for your help.

![Uploading Bildschirmfoto 2022-03-23 um 17.07.07.png…]()
n

**Comment by THDMoritzEnderle** [comment]
Hi Berthold,

I just uploaded an updated version of the script. 
Login is handled by opening the browser at step one. You will then need to log in manually and press return in the console.

I hope this will help you out. Please note that this script is not well maintained since Lovember 2021.

**Comment by Berthold38** [comment]
Thank you very much. Unfortunately, I get an another error: 
"19:38:32 : image index out of range".
I'm not good enough to fix it, I guess it happens in the "parse_first_screenshot" method.

**Comment by THDMoritzEnderle** [comment]
I'm guessing that your monitor resolution is the issue. The code was developed to work on only specific resolutions. 

Can you tell me the OS and the monitors resolution? (As well as scale on windows)

**Comment by Berthold38** [comment]
I'm using Mac OS 12.0.1 on a Mac Book Pro Mid 2012 Screen Resolution is 1280x800. I don't know what you mean with scale on windows.

**Comment by THDMoritzEnderle** [comment]
Okay, it is only optimised for windows as i did not have access to test in on a mac. Your screen resolution is not supported as well.

To fix the issues, you would need to modify the code. As I told you, I am not maintaining the code and will not implement the needed functionalities. You may want to look for an alternative repo

**Comment by Berthold38** [comment]
Hi Moritz, okay, thx .I will look if I find anything else. greetings
